#ifndef KURSI_VIEW_H
#define KURSI_VIEW_H

#include <windows.h>
#include "message_view.h"

#define HEIGHT_KURSI 3
#define WIDTH_KURSI 7
#define POSISI_AWAL_KURSI_TOP 10
#define POSISI_AWAL_KURSI_LEFT 20
#define POSISI_AWAL_KURSI_RIGHT (POSISI_AWAL_KURSI_LEFT + WIDTH_KURSI)
#define POSISI_AWAL_KURSI_BOTTOM (POSISI_AWAL_KURSI_TOP + HEGIHT_KURSI)
#define JUMLAH_TAMPILAN_BARIS_KURSI 10
#define JUMLAH_TAMPILAN_KOLOM_KURSI 15
#define JUMLAH_TAMPILAN_KURSI_MAKS (JUMLAH_TAMPILAN_BARIS_KURSI*JUMLAH_TAMPILAN_KOLOM_KURSI)
SMALL_RECT posisi_kursi[JUMLAH_TAMPILAN_KURSI_MAKS];
HANDLE out;
COORD size_kursi = (COORD){WIDTH_KURSI, HEIGHT_KURSI};
COORD pusat = {0,0};
 





#endif /*KURSI_VIEW_H*/